export const posts = [
    {
        _createdAt: new Date(),
        views: 122,
        author: { _id: 2, name: "Jane Doe" },
        _id: 2,
        description: "Exploring how AI is reshaping the future of automation.",
        image: "https://example.com/images/ai-automation.jpg",
        imgUrl: "https://random-image-pepebigotes.vercel.app/api/random-image",
        category: "Artificial Intelligence",
        title: "The Rise of Smart Machines",
    },
    {
        _createdAt: new Date(),
        views: 89,
        author: { _id: 3, name: "John Smith" },
        _id: 3,
        description: "A deep dive into robotic arms used in manufacturing.",
        image: "https://example.com/images/robotic-arm.jpg",
        imgUrl: "https://random-image-pepebigotes.vercel.app/api/random-image",
        category: "Robots",
        title: "Precision Robotics in Industry",
    },
    {
        _createdAt: new Date(),
        views: 203,
        author: { _id: 4, name: "Alice Johnson" },
        _id: 4,
        description:
            "Drones are more than just flying cameras—here's how they're changing logistics.",
        image: "https://example.com/images/drone-logistics.jpg",
        imgUrl: "https://random-image-pepebigotes.vercel.app/api/random-image",
        category: "Drones",
        title: "Drones and the Delivery Revolution",
    },
    {
        _createdAt: new Date(),
        views: 47,
        author: { _id: 5, name: "Bob Lee" },
        _id: 5,
        description:
            "Understanding the ethical dilemmas posed by autonomous robots.",
        image: "https://example.com/images/robot-ethics.jpg",
        imgUrl: "https://random-image-pepebigotes.vercel.app/api/random-image",
        category: "Ethics",
        title: "Can Robots Make Moral Choices?",
    },
    {
        _createdAt: new Date(),
        views: 150,
        author: { _id: 6, name: "Charlie Brown" },
        _id: 6,
        description:
            "Inside look at humanoid robots that mimic human movement and behavior.",
        image: "https://example.com/images/humanoid.jpg",
        imgUrl: "https://random-image-pepebigotes.vercel.app/api/random-image",
        category: "Humanoids",
        title: "Humanoids: Blurring the Line Between Man and Machine",
    },
];